### ISSUE TITLE
Sometimes 'run' command fails, probably due to slow git

### ISSUE THREAD

**Issue by VladRassokhin** [jonnyzzz/teamcity-rr#1]
Whole output:
```text
TeamCity RR v0.0.42 by @jonnyzzz

Running in /Users/vlad/devel/idea-sources/master...
Using git version: 2.26.2
Current state: 64815a0ec86ce36166319c4f743029c7fd5134a0 from branch master
2 [main] ERROR com.jonnyzzz.teamcity.rr.RRMain  - Unexpected failure: Failed to wait for the process to complete!
java.lang.IllegalStateException: Failed to wait for the process to complete!
	at com.jonnyzzz.teamcity.rr.ExecKt.execWithOutput(exec.kt:43)
	at com.jonnyzzz.teamcity.rr.ExecKt.execWithOutput$default(exec.kt:18)
	at com.jonnyzzz.teamcity.rr.GitKt.listGitCommits(git.kt:95)
	at com.jonnyzzz.teamcity.rr.GitKt.listGitCommits$default(git.kt:93)
	at com.jonnyzzz.teamcity.rr.GitKt.createRRBranch(git.kt:59)
	at com.jonnyzzz.teamcity.rr.RRMainKt.startNewBuild(RRMain.kt:78)
	at com.jonnyzzz.teamcity.rr.RRMainKt.theMain(RRMain.kt:68)
	at com.jonnyzzz.teamcity.rr.RRMainKt.access$theMain(RRMain.kt:1)
	at com.jonnyzzz.teamcity.rr.RRMain.main(RRMain.kt:43)
```
Since I'm running it on MacBook Air Mid 2013, it may be affected by slow git operations.
Meanwhile second invocation succeed.

**Comment by jonnyzzz** [comment]
I guess it could be starvation because of incorrect use of `runBlocking` inside coroutines. Let me check

**Comment by jonnyzzz** [comment]
I've pushed recent changes, please give it yet another try

**Comment by jonnyzzz** [comment]
I've also increased the timeout. That is quite strange that the 

```
GIT_COMMAND, "log", "-$commits", "--topo-order", "--format=%H", head
```
 
command did not complete in 15 seconds. 

You may probably need running the `git gc --force` at some point. To ensure there are not too many files under the `.git` folder of the IJ repo.
